# Generated by Django 2.2.1 on 2019-06-20 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('codigoDep', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estReg', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('codigoDist', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estReg', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='GrupSang',
            fields=[
                ('codigoGS', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('estReg', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioCab',
            fields=[
                ('codigoHor', models.IntegerField(primary_key=True, serialize=False)),
                ('dia', models.IntegerField()),
                ('turno', models.IntegerField()),
                ('fechaIicio', models.DateTimeField(auto_now=True)),
                ('fechaFin', models.DateTimeField()),
                ('estReg', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codigoPro', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estReg', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('codigoPac', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField()),
                ('nombres', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('sexo', models.CharField(max_length=1)),
                ('fechaNac', models.DateTimeField()),
                ('foto', models.BinaryField()),
                ('celular', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=9)),
                ('estadoCivil', models.CharField(max_length=15)),
                ('gradoInstruccion', models.CharField(max_length=15)),
                ('ocupacion', models.CharField(max_length=30)),
                ('fechaReg', models.DateTimeField(auto_now=True)),
                ('direccion', models.CharField(max_length=90)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estReg', models.CharField(max_length=1)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.Departamento')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.Distrito')),
                ('grupoSanguineo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.GrupSang')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.Provincia')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField()),
                ('fechaIicio', models.DateTimeField(auto_now=True)),
                ('fechaFin', models.DateTimeField()),
                ('estReg', models.CharField(max_length=1)),
                ('codigoHor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Admision.HorarioCab')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaCab',
            fields=[
                ('numeroHistoria', models.IntegerField(primary_key=True, serialize=False)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Admision.Paciente')),
            ],
        ),
    ]
