# Generated by Django 2.2.1 on 2019-06-28 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0002_auto_20190628_0241'),
        ('Admision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariocab',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='horariocab',
            name='fechaIicio',
        ),
        migrations.RemoveField(
            model_name='horariodet',
            name='fechaFin',
        ),
        migrations.RemoveField(
            model_name='horariodet',
            name='fechaIicio',
        ),
        migrations.RemoveField(
            model_name='horariodet',
            name='personal',
        ),
        migrations.AddField(
            model_name='horariocab',
            name='dias',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariocab',
            name='fechaInicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horariocab',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrador.Personal'),
        ),
        migrations.AddField(
            model_name='horariodet',
            name='hora_fin',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='horariodet',
            name='hora_inicio',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='codigoDep',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='codigoDist',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='distrito',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='grupsang',
            name='codigoGS',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grupsang',
            name='descripcion',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='historiacab',
            name='paciente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admision.Paciente'),
        ),
        migrations.AlterField(
            model_name='horariocab',
            name='codigoHor',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='horariocab',
            name='fechaFin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariocab',
            name='turno',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horariodet',
            name='codigoHor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admision.HorarioCab'),
        ),
        migrations.AlterField(
            model_name='horariodet',
            name='dia',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='codigoPac',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admision.Departamento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admision.Distrito'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estadoCivil',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fechaNac',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='foto',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='gradoInstruccion',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='grupoSanguineo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admision.GrupSang'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admision.Provincia'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigoPro',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
