# Generated by Django 2.2.1 on 2019-06-20 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('codigoArea', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('estReg', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('codigoTU', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estReg', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('codigoPer', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField()),
                ('nombres', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('celular', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=9)),
                ('direccion', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('estReg', models.CharField(max_length=1)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Administrador.Personal')),
                ('nombreUser', models.IntegerField()),
                ('password', models.IntegerField()),
                ('fechaIicio', models.DateTimeField(auto_now=True)),
                ('estReg', models.CharField(max_length=1)),
                ('tipoUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.TipoUsuario')),
            ],
        ),
    ]
