# Generated by Django 2.2.1 on 2019-06-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='fechaIicio',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_registro',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='codigoArea',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personal',
            name='celular',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='personal',
            name='codigoPer',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personal',
            name='direccion',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AlterField(
            model_name='personal',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='personal',
            name='telefono',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='codigoTU',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombreUser',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=30),
        ),
    ]
