# Generated by Django 2.2.1 on 2019-06-20 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admision', '0001_initial'),
        ('Administrador', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('codigoCita', models.IntegerField(primary_key=True, serialize=False)),
                ('numeroRecibo', models.IntegerField()),
                ('fechaSeparacion', models.DateTimeField()),
                ('fechaAtencion', models.DateTimeField()),
                ('estadoCita', models.CharField(max_length=10)),
                ('turno', models.CharField(max_length=10)),
                ('condicion', models.CharField(max_length=10)),
                ('estReg', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('codigoConsulta', models.IntegerField(primary_key=True, serialize=False)),
                ('horaEntrada', models.DateTimeField()),
                ('horaSalida', models.DateTimeField()),
                ('motivoConsulta', models.CharField(max_length=100)),
                ('apetito', models.CharField(max_length=100)),
                ('orina', models.CharField(max_length=100)),
                ('deposiciones', models.CharField(max_length=100)),
                ('examenFisico', models.CharField(max_length=100)),
                ('diagnostico', models.CharField(max_length=200)),
                ('tratamiento', models.CharField(max_length=300)),
                ('proximaCita', models.DateTimeField()),
                ('estReg', models.CharField(max_length=1)),
                ('estadoAtencion', models.CharField(max_length=1)),
                ('motivoAnulacion', models.TextField()),
                ('cita', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Cita')),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('codigoEsp', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('estReg', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Triaje',
            fields=[
                ('codigoTriaje', models.IntegerField(primary_key=True, serialize=False)),
                ('talla', models.FloatField()),
                ('peso', models.FloatField()),
                ('temperatura', models.FloatField()),
                ('frecuenciaR', models.IntegerField()),
                ('frecuenciaC', models.IntegerField()),
                ('presionArt', models.IntegerField()),
                ('fechaReg', models.DateTimeField()),
                ('estReg', models.CharField(max_length=1)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.Paciente')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administrador.Personal')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Consulta')),
                ('numeroHistoria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Admision.HistoriaCab')),
            ],
        ),
        migrations.CreateModel(
            name='Especialista',
            fields=[
                ('personal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Administrador.Personal')),
                ('estReg', models.CharField(max_length=1)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Especialidad')),
            ],
        ),
        migrations.AddField(
            model_name='consulta',
            name='triaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Triaje'),
        ),
        migrations.AddField(
            model_name='cita',
            name='especialidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Especialidad'),
        ),
        migrations.AddField(
            model_name='cita',
            name='especialista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Especialista'),
        ),
        migrations.AddField(
            model_name='cita',
            name='historia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.HorarioCab'),
        ),
    ]
