# Generated by Django 2.2.1 on 2019-06-28 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Consultorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='codigoCita',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cita',
            name='condicion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Especialidad'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='especialista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Especialista'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='estadoCita',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fechaAtencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fechaSeparacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='historia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admision.HistoriaCab'),
        ),
        migrations.AlterField(
            model_name='cita',
            name='numeroRecibo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='turno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='apetito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='cita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Cita'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='codigoConsulta',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='deposiciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='diagnostico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='estadoAtencion',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='examenFisico',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horaEntrada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='horaSalida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivoAnulacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='motivoConsulta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='orina',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='proximaCita',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='tratamiento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='triaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Triaje'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='codigoEsp',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='especialista',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Consultorio.Especialidad'),
        ),
        migrations.AlterField(
            model_name='historiadet',
            name='numeroHistoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admision.HistoriaCab'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='codigoTriaje',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='fechaReg',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admision.Paciente'),
        ),
        migrations.AlterField(
            model_name='triaje',
            name='personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrador.Personal'),
        ),
    ]
